In [1]:
import os
import sys

In [2]:
import numpy
import aesara.tensor as aet
from aesara import function
import aesara
aesara.__version__

'2.0.4'

In [3]:
import aesara
aesara.__file__
aesara.__version__

'2.0.4'

In [4]:
python -c "import numpy; numpy.test()"
python -c "import scipy; scipy.test()"
pip install pytest
AESARA_FLAGS='' pytest tests/

SyntaxError: invalid syntax (<ipython-input-4-a8ba4ac8a51e>, line 1)

In [5]:
import aesara
from aesara import tensor as aet
from aesara.printing import debugprint

# Declare two symbolic floating-point scalars
a = aet.dscalar("a")
b = aet.dscalar("b")

# Create a simple example expression
c = a + b

# Convert the expression into a callable object that takes `(a, b)`
# values as input and computes the value of `c`.
f_c = aesara.function([a, b], c)

assert f_c(1.5, 2.5) == 4.0

In [6]:
x = aet.dscalar('x')
y = aet.dscalar('y')
z = x + 1 #+ y
f = function([x], z)
f(2)

array(3.)

In [7]:
import aesara
import aesara.tensor as aet
x = aet.dmatrix('x')
s = 1 / (1 + aet.exp(-x))
logistic = aesara.function([x], s)
logistic([[0, 1], [-1, -2]])
array([[ 0.5       ,  0.73105858],
       [ 0.26894142,  0.11920292]])

NameError: name 'array' is not defined

In [8]:
import aesara
import aesara.tensor as aet
import numpy as np

# define tensor variables
X = aet.vector("X")
W = aet.matrix("W")
b_sym = aet.vector("b_sym")
U = aet.matrix("U")
Y = aet.matrix("Y")
V = aet.matrix("V")
P = aet.matrix("P")

results, updates = aesara.scan(lambda y, p, x_tm1: aet.tanh(aet.dot(x_tm1, W) + aet.dot(y, U) + aet.dot(p, V)),
          sequences=[Y, P[::-1]], outputs_info=[X])
compute_seq = aesara.function(inputs=[X, W, Y, U, P, V], outputs=results)

# test values
x = np.zeros((2), dtype=aesara.config.floatX)
x[1] = 1
w = np.ones((2, 2), dtype=aesara.config.floatX)
y = np.ones((5, 2), dtype=aesara.config.floatX)
y[0, :] = -3
u = np.ones((2, 2), dtype=aesara.config.floatX)
p = np.ones((5, 2), dtype=aesara.config.floatX)
p[0, :] = 3
v = np.ones((2, 2), dtype=aesara.config.floatX)

print(compute_seq(x, w, y, u, p, v))

# comparison with numpy
x_res = np.zeros((5, 2), dtype=aesara.config.floatX)
x_res[0] = np.tanh(x.dot(w) + y[0].dot(u) + p[4].dot(v))
for i in range(1, 5):
    x_res[i] = np.tanh(x_res[i - 1].dot(w) + y[i].dot(u) + p[4-i].dot(v))
print(x_res)

[[-0.99505475 -0.99505475]
 [ 0.96471973  0.96471973]
 [ 0.99998585  0.99998585]
 [ 0.99998771  0.99998771]
 [ 1.          1.        ]]
[[-0.99505475 -0.99505475]
 [ 0.96471973  0.96471973]
 [ 0.99998585  0.99998585]
 [ 0.99998771  0.99998771]
 [ 1.          1.        ]]
